### ISSUE TITLE
Issue with updating acs_engine_config template

### ISSUE THREAD

**Issue by Globegitter** [daniel-rhoades/acs-engine-terraform#1]
Hi,
first of all thanks for putting up this tutorial just getting started with testing kubernetes as well as terraform on Azure and this has been very helpful. This is most likely going to be a bug with terraform but I wanted to check with you first that there is nothing I did wrong on my side.

I deployed the k8s cluster using terraform and that all works well. Now I would like to update the cluster to have 3 nodes rather than 1. I am adding a `worker_vm_count = 3` into `k8s.tfvars` and rerun `terraform apply`. It does seem to update something in the state but it somehow seems that `null_resource.render_acs_engine_config` does not update and nothing depending on that. Are you getting the same behaviour?

**Comment by Globegitter** [comment]
Ahh, I seemed to have gotten somewhere using [triggers](https://www.terraform.io/docs/provisioners/null_resource.html#triggers) - but now getting an error on the `az` command:

```
null_resource.deploy_acs (local-exec): ERROR: At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details. {
null_resource.deploy_acs (local-exec):   "error": {
null_resource.deploy_acs (local-exec):     "code": "PropertyChangeNotAllowed",
null_resource.deploy_acs (local-exec):     "target": "customData",
null_resource.deploy_acs (local-exec):     "message": "Changing property 'customData' is not allowed."
null_resource.deploy_acs (local-exec):   }
null_resource.deploy_acs (local-exec): }  Correlation ID: ...
null_resource.deploy_acs: Still creating... (6m30s elapsed)
Error applying plan:

1 error(s) occurred:

* null_resource.deploy_acs: 1 error(s) occurred:

* Error running command 'az group deployment create --name k8sexample-cluster --resource-group k8sexample --template-file ./$(find _output -name 'azuredeploy.json') --parameters @./$(find _output -name 'azuredeploy.parameters.json')': exit status 1. Output: ERROR: At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details. {
  "error": {
    "code": "PropertyChangeNotAllowed",
    "target": "customData",
    "message": "Changing property 'customData' is not allowed."
  }
}  Correlation ID: ....


Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

It seems `customData` is part of the `osProfile` that installs docker etc. but not sure yet why that changed. Will probably investigate more on Monday.

**Edit**: Also just seeing in the dashboard that I have 3 agents no after having run that update command - so something did work. But yeah deleting it all now and as I said restart on Monday.

**Comment by daniel-rhoades** [comment]
Thanks for feedback.  Sorry I was off ill last week, hence late response.  I will take a look at get back to you as soon as I can.

**Comment by daniel-rhoades** [comment]
Yes, because the ACS Engine is being run outside of Terraform it's behaviour is going to be a bit strange.  I think given the maturity of the ACS engine, I would be doing as you suggest, delete the cluster and re-create.
