### ISSUE TITLE
Change in acs-engine ?

### ISSUE THREAD

**Issue by borgesp** [daniel-rhoades/acs-engine-terraform#4]
Hi Daniel,

First of all, congrats on the tutorial and thank you for making it available, it is certainly very useful, considering the lack of documentation on the topic.
I was trying out your script and I was getting the following error:

```
* Error running command 'acs-engine k8s_rendered.json': exit status 1. Output: Error: unknown command "k8s_rendered.json" for "acs-engine"
Run 'acs-engine --help' for usage.
time="2017-06-01T19:10:27Z" level=fatal msg="unknown command "k8s_rendered.json" for "acs-engine""

```
I believe it might be cause by changes in the `acs-engine`, I updated `main.tf` with the following line:

`command = "acs-engine generate ${var.acs_engine_config_file_rendered}"`

Regards, Pedro Borges

**Comment by daniel-rhoades** [comment]
Thanks Pedro, I'll take a look and see if I get the same error with the latest version of acs-engine

**Comment by daniel-rhoades** [comment]
I've updated this project to reflect the latest ACS changes.
